### ISSUE TITLE
We need LOTS more assets

### ISSUE THREAD

**Issue by ghost** [xordspar0/ortho#3]
Kevin and I did some work today and could really only draw skeleton levels. Need at very least more tiles and non-working objects to give the levels some srtucture.

**Comment by ajboole** [comment]
OK I'm thinking combat will be more important, all we really need is one
level for a completed game

**Comment by ghost** [comment]
Yep. I'll work on creating more stuff on the bottom of the "grasslands.cfg" level after the well fall thing to  continue the level a bit further. Also a little drawing of a well would be nice, if it has space for the player to fall through I'm sure Jordan could orchestrate the collision on that. As of now we just have big "1" blocks where we want the well.
