### ISSUE TITLE
Some enemy ai issues

### ISSUE THREAD

**Issue by ghost** [xordspar0/ortho#5]
- Ghosts cannot climb up slight inclines
- Spiders cannot chase you

**Comment by xordspar0** [comment]
Right, the thing I called "spider" just looks in the direction of the player. The idea was that it is some kind of stationary guard.
The enemy I named "ghost" is just something that goes back and forth when the player is close.

I don't know what kind of enemies we want to have or what their behavior should be like (or if they should be a ghost and a spider). This is just something to start with.

Feel free to add any features, graphics, sounds, and behaviors that seem nessesary.
